// GENERATED by scripts/hash-assets.mjs — do not edit by hand.
// Run `node scripts/hash-assets.mjs` after adding or replacing an image.

const manifest: Record<string, string> = {
  "flags/ae.svg": "/flags/ae.d6dc2945.svg",
  "flags/bg.svg": "/flags/bg.4154054c.svg",
  "flags/cm.svg": "/flags/cm.83fbab09.svg",
  "flags/fr.svg": "/flags/fr.10d8a22c.svg",
  "flags/gb.svg": "/flags/gb.86b3fd55.svg",
  "flags/jp.svg": "/flags/jp.2ec73cc6.svg",
  "flags/pk.svg": "/flags/pk.9c8859a5.svg",
  "flags/us.svg": "/flags/us.9e3aac70.svg",
  "partners/google.webp": "/partners/google.44586173.webp",
  "partners/highlevel.webp": "/partners/highlevel.b7a6de19.webp",
  "partners/iso.webp": "/partners/iso.181b7fb4.webp",
  "partners/linkedin.webp": "/partners/linkedin.9c5641ec.webp",
  "partners/magento.webp": "/partners/magento.12d34658.webp",
  "partners/meta.webp": "/partners/meta.988fe675.webp",
  "partners/odoo.webp": "/partners/odoo.f1a87892.webp",
  "partners/pseb.webp": "/partners/pseb.d6ebc827.webp",
  "partners/shopify.webp": "/partners/shopify.5399c257.webp",
  "partners/woocommerce.webp": "/partners/woocommerce.d4a4037a.webp",
  "sectors/development.webp": "/sectors/development.e783af45.webp",
  "sectors/marketing.webp": "/sectors/marketing.8522c79f.webp",
  "sectors/media.webp": "/sectors/media.5abe5bf1.webp",
  "services/ad-creatives.webp": "/services/ad-creatives.e348fa73.webp",
  "services/crm-erp.webp": "/services/crm-erp.6b9a1b74.webp",
  "services/custom-development.webp": "/services/custom-development.585e1488.webp",
  "services/magento.webp": "/services/magento.e100d959.webp",
  "services/mobile-apps.webp": "/services/mobile-apps.5b79bb88.webp",
  "services/performance-marketing.webp": "/services/performance-marketing.bb3e3dce.webp",
  "services/product-shoots.webp": "/services/product-shoots.0717b909.webp",
  "services/seo.webp": "/services/seo.04fe5891.webp",
  "services/shopify.webp": "/services/shopify.ff2c3d55.webp",
  "services/social-media.webp": "/services/social-media.bfad7268.webp",
  "services/ugc-ads.webp": "/services/ugc-ads.8be0407d.webp",
  "services/video-editing.webp": "/services/video-editing.622ef927.webp",
  "services/video-shoots.webp": "/services/video-shoots.610d1d11.webp",
  "services/wordpress.webp": "/services/wordpress.29721e6d.webp",
  "team/abdul-rehman.webp": "/team/abdul-rehman.891fb02b.webp",
  "team/ernest-ekwoge.webp": "/team/ernest-ekwoge.dd694f87.webp",
  "team/muhammad-adnan.webp": "/team/muhammad-adnan.643d9fd3.webp",
  "why/01-ecommerce.webp": "/why/01-ecommerce.d8e08471.webp",
  "why/02-in-house.webp": "/why/02-in-house.63b8c91b.webp",
  "why/03-data.webp": "/why/03-data.39229732.webp",
  "why/04-reporting.webp": "/why/04-reporting.31edd680.webp",
  "why/05-multilingual.webp": "/why/05-multilingual.c4d36e47.webp",
  "why/06-support.webp": "/why/06-support.1969e5a1.webp",
};

/** Resolve a stable key like "sectors/media.webp" to its hashed public URL. */
export function asset(key: string): string {
  const hit = manifest[key];
  if (!hit) throw new Error(`Unknown asset "${key}" — run: node scripts/hash-assets.mjs`);
  return hit;
}
