// GENERATED by scripts/hash-assets.mjs — do not edit by hand.
// Run `node scripts/hash-assets.mjs` after adding or replacing an image.

const manifest: Record<string, string> = {
  "sectors/development.webp": "/sectors/development.e783af45.webp",
  "sectors/marketing.webp": "/sectors/marketing.8522c79f.webp",
  "sectors/media.webp": "/sectors/media.5abe5bf1.webp",
  "why/01-ecommerce.webp": "/why/01-ecommerce.d8e08471.webp",
  "why/02-in-house.webp": "/why/02-in-house.63b8c91b.webp",
  "why/03-data.webp": "/why/03-data.39229732.webp",
  "why/04-reporting.webp": "/why/04-reporting.31edd680.webp",
  "why/05-multilingual.webp": "/why/05-multilingual.c4d36e47.webp",
  "why/06-support.webp": "/why/06-support.1969e5a1.webp",
};

/** Resolve a stable key like "sectors/media.webp" to its hashed public URL. */
export function asset(key: string): string {
  const hit = manifest[key];
  if (!hit) throw new Error(`Unknown asset "${key}" — run: node scripts/hash-assets.mjs`);
  return hit;
}
